version: '3.3'
services:
    zfile:
        container_name: zfile
        restart: always
        ports:
            - '8117:8080'
        volumes:
            - './db:/root/.zfile-v4/db'
            - './logs:/root/.zfile-v4/logs'
            - './application.properties:/root/application.properties'
            - '<YOUR_PATH>:/data/file'
        image: zhaojun1998/zfile