version: '3.3'
services:
  aliyundrive-webdav:
    container_name: aliyundrive-webdav
    restart: unless-stopped
    ports:
      - '8117:8080'
    environment:
      - 'REFRESH_TOKEN=<YOUR_TOKEN>'
      - 'WEBDAV_AUTH_USER=admin'
      - 'WEBDAV_AUTH_PASSWORD=admin'
    image: messense/aliyundrive-webdav:latest